#!/bin/bash
# postrm script for vmagent
#

set -e

if [ -f /usr/share/debconf/confmodule ]; then
  . /usr/share/debconf/confmodule
fi

case "$1" in

  purge|remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
  ;;

  *)
    echo "postrm called with unknown argument '$1'" 1>&2
    exit 1
  ;;

esac

if [ "$1" = "purge" ]; then
    userdel vmagent || true
    if [ -f /usr/local/victoriametrics/vmagent/prometheus.yaml ]; then
        rm -f /usr/local/victoriametrics/vmagent/prometheus.yaml
    fi
fi

# Automatically added by dh_systemd_start/12.10ubuntu1
if [ -d /run/systemd/system ]; then
    systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_systemd_start/12.10ubuntu1
if [ -d /run/systemd/system ]; then
    systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_systemd_enable/12.10ubuntu1
if [ "$1" = "remove" ]; then
    if [ -x "/usr/bin/deb-systemd-helper" ]; then
	deb-systemd-helper mask 'vmagent.service' >/dev/null || true
    fi
fi

if [ "$1" = "purge" ]; then
    if [ -x "/usr/bin/deb-systemd-helper" ]; then
	deb-systemd-helper purge 'vmagent.service' >/dev/null || true
	deb-systemd-helper unmask 'vmagent.service' >/dev/null || true
    fi
fi
# End automatically added section


exit 0