#!/bin/bash
# postinst script for vmagent
#
# see: dh_installdeb(1)

if [ -f /usr/share/debconf/confmodule ]; then
    . /usr/share/debconf/confmodule
fi
if [ -f /usr/local/victoriametrics/vmagent/bin/vmagent-prod ]; then
    ln -s -f /usr/local/victoriametrics/vmagent/bin/$file /usr/sbin/$file
else
    echo "/usr/sbin/vmagent-prod is already present"
fi

case "$1" in
    configure)
      chown -R victoriametrics:vmagent /usr/local/victoriametrics/vmagent
      if [ ! -f /usr/local/victoriametrics/vmagent/prometheus.yaml ]; then
          install -d -m 0755 /usr/local/victoriametrics/vmagent/config
          install -m 0660 -o victoriametrics -g vmagent /dev/null /usr/local/victoriametrics/vmagent/prometheus.yaml
      fi
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

# Automatically added by dh_systemd_enable/12.10ubuntu1
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
    # This will only remove masks created by d-s-h on package removal.
    deb-systemd-helper unmask 'vmagent.service' >/dev/null || true

    # was-enabled defaults to true, so new installations run enable.
    if deb-systemd-helper --quiet was-enabled 'vmagent.service'; then
	# Enables the unit on first installation, creates new
	# symlinks on upgrades if the unit file has changed.
	deb-systemd-helper enable 'vmagent.service' >/dev/null || true
    else
	# Update the statefile to add new symlinks (if any), which need to be
	# cleaned up on purge. Also remove old symlinks.
	deb-systemd-helper update-state 'vmagent.service' >/dev/null || true
    fi
fi
# End automatically added section
# Automatically added by dh_systemd_start/12.10ubuntu1
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
    if [ -d /run/systemd/system ]; then
	systemctl --system daemon-reload >/dev/null || true
	if [ -n "$2" ]; then
	    _dh_action=restart
	else
	    _dh_action=start
	fi
	deb-systemd-invoke $_dh_action 'vmagent.service' >/dev/null || true
    fi
fi
# End automatically added section
# Automatically added by dh_systemd_start/12.10ubuntu1
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
    if [ -d /run/systemd/system ]; then
	systemctl --system daemon-reload >/dev/null || true
	deb-systemd-invoke start 'vmagent.service' >/dev/null || true
    fi
fi
# End automatically added section


exit 0