#!/bin/sh
# kFreeBSD do not accept scripts as interpreters, using #!/bin/sh and sourcing.
if [ true != "$INIT_D_SCRIPT_SOURCED" ] ; then
    set "$0" "$@"; INIT_D_SCRIPT_SOURCED=true . /lib/init/init-d-script
fi
### BEGIN INIT INFO
# Provides:          victoria-metrics
# Required-Start:    $remote_fs
# Required-Stop:     $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: fast, cost-effective and scalable time series database
# Description:       VictoriaMetrics is a systems and services monitoring
#                    system. It can be used as long-term remote storage for
#                    Prometheus. It collects metrics from configured targets
#                    at given intervals, evaluates rule expressions, displays
#                    the results, and can trigger alerts if some condition is
#                    observed to be true.
### END INIT INFO

# Author: Guillem Jover <gjover@sipwise.com>

DESC="monitoring system and time series database"
NAME=victoria-metrics
USER=_$NAME
GROUP=_$NAME
DAEMON=/usr/bin/$NAME
PIDFILE=/run/$NAME/$NAME.pid
LOGFILE=/var/log/$NAME/$NAME.log

START_ARGS="--no-close --background --make-pidfile"
STOP_ARGS="--remove-pidfile"

do_start_prepare()
{
    mkdir -p $(dirname $PIDFILE)
}

do_start_cmd_override()
{
    start-stop-daemon --start --quiet --oknodo \
        --exec $DAEMON --pidfile $PIDFILE --user $USER --group $GROUP \
        --chuid $USER:$GROUP $START_ARGS -- $ARGS >>$LOGFILE 2>&1
}

do_stop_cmd_override()
{
    start-stop-daemon --stop --quiet --oknodo --retry=TERM/30/KILL/5 \
        --exec $DAEMON --pidfile $PIDFILE --user $USER $STOP_ARGS
}

alias do_reload=do_reload_sigusr1
